sequenceDiagram
    actor user

    participant authn-service
    participant database
    participant kafka

    user->>authn-service: Login with username and password.<br>Optionally a redirect url
    authn-service->>database: Get the number of consecutive failed login attempts
    database-->>authn-service: Number of consecutive failed login attempts

    alt 5 consecutive failed attempts
        authn-service->>database: Lock user for 1 hour
        database-->>authn-service: Acknowledge
        authn-service->>user: HTTP:403 Show message of user locked<br>try after 1 hour
    else <5 consecutive failed attempts
        authn-service->>database: Validate user is not locked and username and password is valid
        alt Authentication is not successful
            authn-service->>database: Increment failed login attempts
            authn-service->>database: Lock user if more then 5 failed login attempts
            authn-service->>user: HTTP:401 Unauthenticated
        else Authentication is successful
            authn-service->>database: Reset failed login attempts
            authn-service->>database: Reset user lock state
            authn-service->>database: Generate
        end
    end



